### ISSUE TITLE
webpac will not handle $c

### ISSUE THREAD

**Issue by maryakem** [maryakem/CULib#1]
we loaded some records from the CBC that include subfield $c.  These should display with the preceding cataloguing punctuation for catalogue records  /

e.g. http://library.capilanou.ca/record=b1028431~S1

Let me know if you have questions.  Thanks for taking a look at this issue.

**Comment by ggreenly** [comment]
Looking at original load file from vendor.  Records I looked at lack slash "/" in preceding subfield before $c subfield.  Should it not be present? Another load file from another vendor has this punctuation present.  What have I missed?  We could do some regex in Global update to add missing punctuation to records if desired probably.  Webpac from what I see displays what punctuation is present in the record but does not supply it.  I'll check documentation if you want me to or open a ticket with III.

**Comment by maryakem** [comment]
@ggreenly you have not missed anything.  Perfect diagnosis.  We'll go back and settle on the best fix for this.

**Comment by maryakem** [comment]
I will batch delete edit in MarcEdit and will reload with HB thanks
